OpheliasOasis/OpheliasOasis/Models/ReservationType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpheliasOasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationType()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int resTypeId { get; set; }
        public string resType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
    }
}

OpheliasOasis/OpheliasOasis/Models/creditCard.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpheliasOasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditCard
    {
        public int ID { get; set; }
        public int guestID { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public int securityCode { get; set; }
    
        public virtual guest guest { get; set; }
    }
}

OpheliasOasis/OpheliasOasis/Models/reservation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpheliasOasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.reservationDays = new HashSet<reservationDay>();
            this.reservationPenalties = new HashSet<reservationPenalty>();
        }
    
        public int ID { get; set; }
        public int guestID { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public Nullable<System.DateTime> leaveDate { get; set; }
        public Nullable<System.DateTime> checkInDate { get; set; }
        public Nullable<System.DateTime> checkOutDate { get; set; }
        public Nullable<int> room { get; set; }
        public bool noShow { get; set; }
        public bool isCancelled { get; set; }
        public Nullable<System.DateTime> paidDate { get; set; }
        public Nullable<double> prepaidCharge { get; set; }
        public int typeID { get; set; }
        public decimal total { get; set; }
    
        public virtual guest guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationDay> reservationDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationPenalty> reservationPenalties { get; set; }
        public virtual ReservationType ReservationType { get; set; }
    }
}

OpheliasOasis/OpheliasOasis/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OpheliasOasis.Models;
using OpheliasOasis.ViewModels;

namespace OpheliasOasis.Controllers
{
	public class HotelController : Controller
	{
		HotelDBEntitiesMDF db = new HotelDBEntitiesMDF(); // Database connection db

		// GET: Hotel
		public ActionResult Index()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "Index";
                return RedirectToAction("Login");
            }


            return View();
		}
		
		// GET: Hotel/Reservation
		public ActionResult Reservation()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "Reservation";
                return RedirectToAction("Login");
            }
            ReservationPageViewModel resVM = new ReservationPageViewModel();

			// Setup SelectList for DropDownBox
			List<reservation> currentReserve = db.reservations.ToList();
			resVM.CurrentReserve = new SelectList(currentReserve, "ID", "ID");

			return View(resVM);
		}

		public ActionResult EditRecord(ReservationPageViewModel model, IEnumerable<bool> noShow, IEnumerable<bool> isCancelled)
		{

			if (noShow != null && noShow.Count() == 2)
			{
				model.noShow = true;
			}
			else
			{
				model.noShow = false;
			}

			if (isCancelled != null && isCancelled.Count() == 2)
			{
				model.isCancelled = true;
			}
			else
			{
				model.isCancelled= false;
			}

			try
			{

				reservation resData = db.reservations.SingleOrDefault(x => x.ID == model.ID);
				guest guestData = db.guests.SingleOrDefault(y => y.ID == resData.guestID);

  
				guestData.firstName = model.firstName;
				guestData.lastName = model.lastName;
				resData.checkInDate = model.checkInDate;
				resData.checkOutDate = model.checkOutDate;
				guestData.email = model.email;
				resData.arrivalDate = model.arrivalDate;
				resData.leaveDate = model.leaveDate;
				resData.room = model.room;
				resData.isCancelled = model.isCancelled;
				resData.paidDate = model.paidDate;
				resData.noShow = model.noShow;

				db.SaveChanges();

			}
			catch (Exception ex)
			{
				throw ex;
			}

			return RedirectToAction("Index");
		}

		// GET: Hotel/Reservation
		public ActionResult Login()
		{
			LoginPageViewModel loginVM = new LoginPageViewModel();

			if (TempData["LoginView"] != null)
			{
				// Preserves view from 
				loginVM = (LoginPageViewModel)TempData["LoginView"];

				List<employee> userList = db.employees.ToList();
				loginVM.employees = userList;
				loginVM.employeeSelect = new SelectList(userList, "ID", "name");
			}
			else
			{
				// Setup SelectList for DropDownBox
				List<employee> userList = db.employees.ToList();
				loginVM.employees = userList;
				loginVM.employeeSelect = new SelectList(userList, "ID", "name");
				loginVM.message = LoginPageViewModel.START_TEXT;
				loginVM.messageColor = "#000000";
			}


			return View(loginVM);
		}

		public ActionResult LoginUser(LoginPageViewModel model)
		{
			string password = model.password;
			int empID = model.empID;

			List<employee> userList = db.employees.ToList();
			foreach (employee e in userList)
			{
				if (e.ID == empID && e.password == password)
				{
                    this.Session["CurrentUser"] = e;
                    if (TempData["LoginRedirect"] == null)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction((string)TempData["LoginRedirect"]);
                    }
				} 
			}

			model.message = LoginPageViewModel.FAIL_TEXT;
			model.messageColor = "#FF0000";

			TempData["LoginView"] = model;

			return RedirectToAction("Login");
		}

        public ActionResult GenerateEmail()
        {
            EmailPageViewModel emailVM = new EmailPageViewModel();

            return View(emailVM);
        }

		public ActionResult SaveRecord(ReservationPageViewModel model)
		{
			try
			{

				reservation resData = new reservation();
				guest guestData = new guest();

				guestData.firstName = model.firstName;
				guestData.lastName = model.lastName;
				resData.checkInDate = model.checkInDate;
				resData.checkOutDate = model.checkOutDate;
				guestData.email = model.email;
				resData.typeID = model.typeID;

				db.guests.Add(guestData);
				db.reservations.Add(resData);


				db.SaveChanges();

				guestData = db.guests.SingleOrDefault(y => y.lastName == model.lastName && y.firstName == model.firstName && y.email == model.email);
				resData = db.reservations.SingleOrDefault(x => x.checkInDate == model.checkInDate && x.guestID == guestData.ID);
				var resID = resData.ID;

				db.createEachReservationDay(model.checkInDate, model.checkOutDate, resID);
			}
			catch(Exception ex)
			{
				throw ex;
			}

			return RedirectToAction("Index");
		}

		// GET: Hotel/ExpectedOccupancyReport
		public ActionResult ExpectedOccupancyReport()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "ExpectedOccupancyReport";
                return RedirectToAction("Login");
            }
            try
			{
				var context = new HotelDBEntitiesMDF();
				var result = context.getExpectedOccupancy();
				return View(result.ToList());
			}
			catch (Exception ex)
			{
				throw ex;
			}

		}

		// GET: Hotel/ExpectedRoomIncomeReport
		public ActionResult ExpectedRoomIncomeReport()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "ExpectedRoomIncomeReport";
                return RedirectToAction("Login");
            }
            try
			{
				var context = new HotelDBEntitiesMDF();
				var result = context.getExpectedIncome();
				return View(result.ToList());
			}
			catch (Exception ex)
			{
				throw ex;
			}

		}

		// GET: Hotel/IncentiveReport
		public ActionResult IncentiveReport()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "IncentiveReport";
                return RedirectToAction("Login");
            }
            try
			{
				var context = new HotelDBEntitiesMDF();
				var result = context.getIncentiveReport();
				return View(result.ToList());
			}
			catch (Exception ex)
			{
				throw ex;
			}

		}

		// GET: Hotel/DailyArrivalsReport
		public ActionResult DailyArrivalsReport()
        {
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "DailyArrivalsReport";
                return RedirectToAction("Login");
            }
            try { 
			List<reservation> resList = db.reservations.ToList();
			var today = DateTime.Today;

			List<DailyArrivalsReportPageViewModel> daReportVMResList = resList.Join(
				db.guests,
				res => res.guestID,
				gue => gue.ID,
				(res,gue) => new {res,gue})
				.Join(db.ReservationTypes,
					o => o.res.typeID,
					type => type.resTypeId,
					(res2,type) => new{res2, type})
				.Where(daReportVM => (daReportVM.res2.res.isCancelled == false)
				&& (daReportVM.res2.res.noShow == false)
				&& (daReportVM.res2.res.checkInDate == today))
				.OrderBy(daReportVM => daReportVM.res2.gue.lastName)
				.ThenBy(daReportVM => daReportVM.res2.gue.firstName)
				.Select(daReportVM => new DailyArrivalsReportPageViewModel
				{
					firstName = daReportVM.res2.gue.firstName,
					lastName = daReportVM.res2.gue.lastName,
					room = daReportVM.res2.res.room,
					resType = daReportVM.type.resType,
					checkOutDate = daReportVM.res2.res.checkOutDate
				}).ToList();

				return View(daReportVMResList);
			}
			catch (Exception ex)
			{
				throw ex;
			} 

		}

		// GET: Hotel/DailyOccupancyReport
		public ActionResult DailyOccupancyReport()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "DailyOccupancyReport";
                return RedirectToAction("Login");
            }
            try { 
			List<reservation> resList = db.reservations.ToList();
			var today = DateTime.Today;

			List<DailyOccupancyReportPageViewModel> doReportVMResList = resList.Join(
				db.guests,
				res => res.guestID,
				gue => gue.ID,
				(res, gue) => new { res, gue })
				.Where(doReportVM => (doReportVM.res.checkInDate < today)
					&& (doReportVM.res.checkOutDate >= today)
					&& (doReportVM.res.isCancelled == false)
					&& (doReportVM.res.noShow == false))
				.OrderBy(doReportVM => doReportVM.res.room)
				.Select(doReportVM => new DailyOccupancyReportPageViewModel
				{
					firstName = doReportVM.gue.firstName,
					lastName = doReportVM.gue.lastName,
					room = doReportVM.res.room,
					checkOutDate = doReportVM.res.checkOutDate
				}).ToList();

				return View(doReportVMResList);
			}
			catch (Exception ex)
			{
				throw ex;
			}

		}

		[HttpGet]
		public ActionResult ReservationForm()
		{
            if (this.Session["CurrentUser"] == null)
            {
                TempData["LoginRedirect"] = "ReservationForm";
                return RedirectToAction("Login");
            }
            ReservationPageViewModel resVM = new ReservationPageViewModel();

			// Setup SelectList for DropDownBox
			List<ReservationType> resList = db.ReservationTypes.ToList();
			resVM.resListItems = new SelectList(resList, "resTypeId", "resType");

			

			return PartialView("_ReservationForm", resVM);
		}

		[HttpPost]
		public ActionResult EditReservation(int currentRes)
		{
			int currentResInt = Convert.ToInt32(currentRes);
			ReservationPageViewModel resVM = new ReservationPageViewModel();
			reservation findRes = new reservation();
			guest findGuest = new guest();
			ReservationType type = new ReservationType();

			findRes = db.reservations.SingleOrDefault(y => y.ID == currentRes);

OpheliasOasis/OpheliasOasis/Views/Hotel/CreditCard.cshtml
@model OpheliasOasis.ViewModels.CreditCardPageViewModel
@{
    ViewBag.Title = "Credit Card";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="padding: 20px 0;">
    Credit Card
    <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
</h2>

<div>

    <div id="findGuest">
        @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "Email", @id = "findEmail"})
        <br />
        <button class="btn btn-outline-dark" id="findGuestBtn">Find Guest</button>
    </div>
    

    <div id="editCC"></div>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/DailyArrivalsReport.cshtml
@model IEnumerable<OpheliasOasis.ViewModels.DailyArrivalsReportPageViewModel>
@{
    ViewBag.Title = "Daily Arrivals Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2 style="padding: 20px 0;">
        Daily Arrivals Report
        <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
    </h2>

<div>

    <table class="table table-striped table-dark text-center">
        <thead class="thead-light">
            <tr>
                <th scope="col">Guest Name</th>
                <th scope="col">Reservation Type</th>
                <th scope="col">Room</th>
                <th scope="col">Departure Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td  scope="row">@item.firstName @item.lastName</td>
                <td>@item.resType</td>
                <td>@item.room</td>
                <td>@item.checkOutDate</td>
            </tr>
            }
        </tbody>
    </table>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/DailyOccupancyReport.cshtml
@model IEnumerable<OpheliasOasis.ViewModels.DailyOccupancyReportPageViewModel>
@{
    ViewBag.Title = "Daily Occupancy Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2 style="padding: 20px 0;">
        Daily Occupancy Report
        <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
    </h2>

<div>

    <table class="table table-striped table-dark  text-center">
        <thead class="thead-light">
            <tr>
                <th scope="col">Room Number</th>
                <th scope="col">Guest Name</th>
                <th scope="col">Departure Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.room</td>
                    @if (@item.checkOutDate == DateTime.Today) {
                        <td scope="row">*@item.firstName @item.lastName</td>
                    } else {
                        <td scope="row">@item.firstName @item.lastName</td>
                    }
                    <td>@item.checkOutDate</td>
                </tr>
            }
        </tbody>
    </table>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/ExpectedOccupancyReport.cshtml
@model IEnumerable<OpheliasOasis.Models.getExpectedOccupancy_Result>
@{
    ViewBag.Title = "Expected Occupancy Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2 style="padding: 20px 0;">
        Expected Occupancy Report
        <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
    </h2>

<div>

    <table class="table table-striped table-dark text-center">
        <thead class="thead-light">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Total Guests</th>
                <th scope="col">Prepaid</th>
                <th scope="col">Incentive</th>
                <th scope="col">60 Day</th>
                <th scope="col">Conventional</th>
            </tr>
        </thead>
        <tbody>
            @{int sum = 0; }
            @foreach (var item in Model)
            {
                sum += (int)item.count;
                <tr>
                    <td>@item.theDate</td>
                    <td>@item.count</td>
                    <td>@item.prepaid</td>
                    <td>@item.incentive</td>
                    <td>@item.day60</td>
                    <td>@item.conventional</td>
                </tr>
            }
        </tbody>
    </table>
    @{int average = (sum % 30) / 30; sum = sum / 30; }
    <h4>Average Occupancy Rate: @sum.@average</h4>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/ExpectedRoomIncomeReport.cshtml
@model IEnumerable<OpheliasOasis.Models.getExpectedIncome_Result>
@{
    ViewBag.Title = "Expected Room Income Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="padding: 20px 0;">
    Expected Room Income Report 
    <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
</h2>

<div>

    <table class="table table-striped table-dark text-center">
        <thead class="thead-light">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Total Income</th>
            </tr>
        </thead>
        <tbody>
            @{int sum = 0; }
            @foreach (var item in Model)
            {
                sum += (int)item.sum;
                <tr>
                    <td>@item.theDate</td>
                    <td>@item.sum</td>
                </tr>
            }
        </tbody>
    </table>
    <h4>Total Income: @sum</h4>
    @{int average = (sum % 30) / 30; sum = sum / 30; }
    <h4>Average Income: @sum.@average</h4>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/IncentiveReport.cshtml
@model IEnumerable<OpheliasOasis.Models.getIncentiveReport_Result>
@{
    ViewBag.Title = "Incentive Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="padding: 20px 0;">
    Incentive Report
    <a href="/Hotel" class="btn btn-info float-right" role="button">Homepage</a>
</h2>

<div>

    <table class="table table-striped table-dark text-center">
        <thead class="thead-light">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Incentive Income Lost</th>
            </tr>
        </thead>
        <tbody>
            @{int sum = 0; }
            @foreach (var item in Model)
            {
                sum += (int)item.sum;
                <tr>
                    <td>@item.theDate</td>
                    <td>@item.sum</td>
                </tr>
            }
        </tbody>
    </table>
    <h4>Total Incentive Income Lost: @sum</h4>
    @{int average = (sum % 30) / 30; sum = sum / 30; }
    <h4>Average Incentive Income Lost: @sum.@average</h4>

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/_EditCreditCardForm.cshtml
@model OpheliasOasis.ViewModels.CreditCardPageViewModel

    <div>

        @using (Html.BeginForm("SaveCreditCard", "Hotel", FormMethod.Post))
        {

            @Html.HiddenFor(model => model.gID)
            @Html.HiddenFor(model => model.cID)
            <p>@Model.firstName @Model.lastName (@Model.email)</p>
            <label for="name">
                Name on Card:
                @Html.TextBoxFor(model => model.name, new { @class = "form-control", @placeholder = "Name", @value = Model.name })
            </label>
            <label for="number">
                Card Number:
                @Html.TextBoxFor(model => model.number, new { @class = "form-control", @placeholder = "Credit Card Number", @value = Model.number })
            </label>
            <label for="month">
                Month:
                @Html.TextBoxFor(model => model.month, new { @class = "form-control", @placeholder = "Month", @value = Model.month })
            </label>
            <label for="year">
                Year:
                @Html.TextBoxFor(model => model.year, new { @class = "form-control", @placeholder = "Year", @value = Model.year })
            </label>
            <label for="securityCode">
                Security Code:
                @Html.TextBoxFor(model => model.securityCode, new { @class = "form-control", @placeholder = "Security Code", @value = Model.securityCode })
            </label>

            <input type="submit" value="Submit" class="btn btn-block btn-primary" />

        }

        <br /><br />
        <a href="/Hotel/CreditCard" class="btn btn-info" role="button">Back</a>

    </div>

    <style>
        label {
            display: block;
        }
    </style>

OpheliasOasis/OpheliasOasis/Views/Hotel/_EditReservation.cshtml
@model OpheliasOasis.ViewModels.ReservationPageViewModel

<div>

    @using (Html.BeginForm("EditRecord", "Hotel", FormMethod.Post))
    {

        @Html.HiddenFor(model => model.ID)
        <h3>Guest Information</h3>
        <div class="form-row">
            @Html.TextBoxFor(model => model.firstName, new { @class = "form-control", @placeholder = "First Name", @value = Model.firstName })
            &nbsp;&nbsp;
            @Html.TextBoxFor(model => model.lastName, new { @class = "form-control", @placeholder = "Last Name", @value = Model.lastName })
        </div>
        <br />
        <div class="form-row">
            @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "Email", @value = Model.email })
        </div>
        <br />
        <h3>Reservation Information</h3>
        <div class="form-row">
            @Html.TextBoxFor(model => model.checkInDate, new { @class = "form-control", @placeholder = "Checkin Date", @value = Model.checkInDate })
            &nbsp;&nbsp;
            @Html.TextBoxFor(model => model.checkOutDate, new { @class = "form-control", @placeholder = "Checkout Date", @value = Model.checkOutDate })
        </div>
        <br />
        <div class="form-row">
            @Html.TextBoxFor(model => model.arrivalDate, new { @class = "form-control", @placeholder = "Arrival Date", @value = Model.arrivalDate })
            &nbsp;&nbsp;
            @Html.TextBoxFor(model => model.leaveDate, new { @class = "form-control", @placeholder = "Exit Date", @value = Model.leaveDate })
        </div>
        <br />
        <div class="form-row">
            @Html.TextBoxFor(model => model.room, new { @class = "form-control", @placeholder = "RoomNumber", @value = Model.room })
        </div>
        <br />
        <div class="form-row">
            &nbsp;
            <label>
                Cancelled:
            </label>
            @Html.CheckBoxFor(model => model.isCancelled, new { @class = "form-control", @value = Model.isCancelled })
            &nbsp;&nbsp;
            <label>
                Tardy:
            </label>
            @Html.CheckBoxFor(model => model.noShow, new { @class = "form-control", @value = Model.noShow })
        </div>
        <br />
        <div class="form-row">
            @Html.TextBoxFor(model => model.paidDate, new { @class = "form-control", @placeholder = "Date of Payment", @value = Model.paidDate })
            &nbsp;&nbsp;
            <input class="form-control" id="resType" name="resType" placeholder="Reservation Type" type="text" value="@Model.resType" disabled />

        </div>
        <br />

        <input type="submit" value="edit" class="btn btn-block btn-primary" />

    }

</div>

OpheliasOasis/OpheliasOasis/Views/Hotel/_NewRateForm.cshtml
@model OpheliasOasis.ViewModels.RatesPageViewModel

    <div>

        @using (Html.BeginForm("SaveNewRate", "Hotel", FormMethod.Post))
        {

            <label for="rate">
                Date:
                @Html.TextBoxFor(model => model.rate, new { @class = "form-control", @placeholder = "Rate" })
            </label>
            <label for="rateDate">
                Rate:
                @Html.TextBoxFor(model => model.rateDate.Date, new { @class = "form-control", @placeholder = "Date" })
            </label>

            <input type="submit" value="Submit" class="btn btn-block btn-primary" />

        }

        <br /><br />
        <a href="/Hotel/Rates" class="btn btn-info" role="button">Back</a>

    </div>

<style>
    label {
        display: block;
    }
</style>

OpheliasOasis/OpheliasOasis/Views/Hotel/_ReservationForm.cshtml
@model OpheliasOasis.ViewModels.ReservationPageViewModel

@{

}

<div>

    @using (Html.BeginForm("SaveRecord", "Hotel", FormMethod.Post))
    {
        <h3>Guest Information</h3>
        <div class="form-row">
            @Html.TextBoxFor(model => model.firstName, new { @class = "form-control", @placeholder = "First Name" })
            &nbsp;&nbsp;
            @Html.TextBoxFor(model => model.lastName, new { @class = "form-control", @placeholder = "Last Name" })
        </div>
        <br />
        <div class="form-row">
            @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "Email" })
        </div>
        <br />
        <h3>Reservation Information</h3>
        <div class="form-row">
            @Html.TextBoxFor(model => model.checkInDate, new { @class = "form-control", @placeholder = "Checkin Date", @value = Model.checkInDate })
            &nbsp;&nbsp;
            @Html.TextBoxFor(model => model.checkOutDate, new { @class = "form-control", @placeholder = "Checkout Date", @value = Model.checkOutDate })
        </div>
        <br />
        <div class="form-row">
            @Html.DropDownListFor(model => model.typeID, Model.resListItems as SelectList, "--Choose Reservation Type--", new { @class = "form-control", @id = "otherID" })
            &nbsp;&nbsp;
            <input disabled type="text" class="form-control" id="totCost" value="$@Model.cost.ToString("F")"/>
        </div>
        <br />
        <input type="submit" value="Submit" class="btn btn-block btn-primary" />

    }

</div>


@Scripts.Render("~/Scripts/ReservationForm.js")